<?php

class Test_Vimeography_Shortcode extends Vimeography_Shortcode
{
  /**
   * Determines which gallery settings to use based on the provided
   * shortcode settings, the existing gallery db settings, and the
   * fallback gallery settings.
   *
   * @return array  The gallery settings to be used to render the current gallery.
   */
  public static function _apply_shortcode_gallery_settings($atts) {
    return parent::_apply_shortcode_gallery_settings($atts);
  }

  /**
   * Verifies that the provided width setting is a valid CSS parameter
   *
   * @param  string $width
   * @return string        A percentage, pixel-based, or empty width value.
   */
  public static function _validate_gallery_width($width) {
    return parent::_validate_gallery_width($width);
  }

  /**
   * Load any custom CSS files that have been generated by the 
   * Vimegraphy theme customization tools.
   * 
   * @return void
   */
  public function _vimeography_enqueue_custom_stylesheets() {
    return $this->_vimeography_enqueue_custom_stylesheets();
  }
}